import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Components
import {Navbar} from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <header className="flex justify-end w-full h-1/12 bg-blue-500">
          <Navbar/>
        </header>

        <main className=" bg-blue-400 h-9/12">
        {children}
        </main>

        <footer className="h-2/12 bg-blue-500">

        </footer>

      </body>
    </html>
  );
}
